name: Slack

on:
  workflow_dispatch:
    inputs:
      message: 
        description: 'post message as text file to slack'
        required: true
        default: 'Hello World!'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo ${{ github.event.inputs.message }} > message.txt'
      - uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: '#testing'
          file_path: 'message.txt'
          file_name: 'message.txt'
          file_type: 'text'
          initial_comment: 'post by slack-upload-file'
